### ISSUE TITLE
Read and write the content of the mount

### ISSUE THREAD

**Issue by ddrachau** [fenio/pv-mounter#5]
I was able to use the plugin to mount my pv locally. The files belong the root user. Even though I mounted everything as root, I am not able to create or delete files.

Should this be possible, or is this module just a mounter for a read only filesystem?

drwxr-xr-x  1 root root    287 Jun 21 22:19 ./
drwxr-xr-x 23 root root   4096 Jun  7 16:11 ../
-rw-r--r--  1 root root      2 Jun 21 22:10 automations.yaml

root@r:/mnt# rm -rf *
rm: cannot remove 'automations.yaml': Permission denied

**Comment by fenio** [comment]
Hey @ddrachau.
Thanks for the report. No it shouldn't be only for read-only filesystem. I'm able to successfully modify files on a locally mounted fs. 
First of all which is the operating system you're using for mount?
Can you also share more details about the PV/PVC?

For start `kubectl describe pvc <the one you try to use>` would be useful.

Is this PVC already mounted by other POD or something with RWX access or unmounted RWO?

**Comment by ddrachau** [comment]
Hey thanks for the reply, I am currently deep in the analysis and appreciate any support :)

I am trying to mount it from an Ubuntu system. Mount is successful, I can cat files, but not touch or remove any files.

The spawned pod is the only one claiming the PVC. I uninstalled the application helm to modify the pv before deploying the application again.

Name:          home-assistant-home-assistant-0
Namespace:     home-assistant
StorageClass:  p
Status:        Bound
Volume:        pvc-83a18b9f-d75c-4660-88af-e0110d0935c9
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       volume-exposer-ibgtr
Events:        <none>

**Comment by ddrachau** [comment]
My mount point is /home/daniel/mnt 

drwxrwxr-x  2 daniel daniel 4096 Jun 21 22:51 mnt/

After running `k pv-mounter mount home-assistant home-assistant-home-assistant-0 mnt` the files are mounted in the mnt folder but they belong to the user and group 0 - but even root is not able to work there

drwxr-xr-x  1 root   root    287 Jun 21 22:19 mnt/

**Comment by fenio** [comment]
Ok maybe for start let's try to check if it is problem with SSHFS or just permissions within the cluster.
Are you able to make write operations on it from volume-ezposer-ibgtr pod?

You can check it by kube execing into it.

`kubectl exec -it volume-exposer-ibgtr -- /bin/sh`
`touch /volume/whatever`

Does it work?

**Comment by ddrachau** [comment]
No, it's not working from the pod either. :(  

`ve@volume-exposer-vaa9y:/volume$ ls -aln`
total 176
drwxr-xr-x 7 0 0    287 Jun 21 20:19 .
drwxr-xr-x 1 0 0     28 Jun 22 18:54 ..
-rw-r--r-- 1 0 0      8 Jun 21 20:10 .HA_VERSION
drwxr-xr-x 2 0 0      6 Jun 21 20:10 .cloud
drwxr-xr-x 2 0 0   4096 Jun 21 20:19 .storage
-rw-r--r-- 1 0 0      2 Jun 21 20:10 automations.yaml
drwxr-xr-x 4 0 0     38 Jun 21 20:10 blueprints
-rw-r--r-- 1 0 0    265 Jun 21 20:10 configuration.yaml
drwxr-xr-x 2 0 0      6 Jun 21 20:10 deps
-rw-r--r-- 1 0 0      0 Jun 21 20:10 home-assistant.log
-rw-r--r-- 1 0 0      0 Jun 21 20:10 home-assistant.log.1
-rw-r--r-- 1 0 0 159744 Jun 21 20:19 home-assistant_v2.db
-rw-r--r-- 1 0 0      0 Jun 21 20:10 scenes.yaml
-rw-r--r-- 1 0 0      0 Jun 21 20:10 scripts.yaml
-rw-r--r-- 1 0 0    161 Jun 21 20:10 secrets.yaml
drwxr-xr-x 2 0 0      6 Jun 21 20:10 tts
`ve@volume-exposer-vaa9y:/volume$ touch test`
touch: cannot touch 'test': Permission denied

**Comment by fenio** [comment]
Ok so at least it's not the problem with SSHFS.
Can you share full output of the following commands?

`kubectl describe pvc home-assistant-home-assistant-0`
`kubectl describe pv pvc-83a18b9f-d75c-4660-88af-e0110d0935c9`

**Comment by ddrachau** [comment]
The pod user is 've' and the mounted pv at /volume belongs to root, could this be a problem?

kubectl describe pvc home-assistant-home-assistant-0 -n home-assistant
Name:          home-assistant-home-assistant-0
Namespace:     home-assistant
StorageClass:  proxmox-data-xfs
Status:        Bound
Volume:        pvc-83a18b9f-d75c-4660-88af-e0110d0935c9
Labels:        app.kubernetes.io/instance=home-assistant
               app.kubernetes.io/name=home-assistant
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: csi.proxmox.sinextra.dev
               volume.kubernetes.io/selected-node: t
               volume.kubernetes.io/storage-provisioner: csi.proxmox.sinextra.dev
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       volume-exposer-vaa9y
Events:        <none>

kubectl describe pv pvc-83a18b9f-d75c-4660-88af-e0110d0935c9
Name:              pvc-83a18b9f-d75c-4660-88af-e0110d0935c9
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: csi.proxmox.sinextra.dev
                   volume.kubernetes.io/provisioner-deletion-secret-name:
                   volume.kubernetes.io/provisioner-deletion-secret-namespace:
Finalizers:        [kubernetes.io/pv-protection external-attacher/csi-proxmox-sinextra-dev]
StorageClass:      proxmox-data-xfs
Status:            Bound
Claim:             home-assistant/home-assistant-home-assistant-0
Reclaim Policy:    Retain
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          5Gi
Node Affinity:
  Required Terms:
    Term 0:        topology.kubernetes.io/zone in [p]
                   topology.kubernetes.io/region in [l]
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            csi.proxmox.sinextra.dev
    FSType:            xfs
    VolumeHandle:      l/p/local-lvm/vm-9999-pvc-83a18b9f-d75c-4660-88af-e0110d0935c9
    ReadOnly:          false
    VolumeAttributes:      storage=local-lvm
                           storage.kubernetes.io/csiProvisionerIdentity=1718192305411-36-csi.proxmox.sinextra.dev
Events:                <none>

**Comment by fenio** [comment]
Well yeah this could be a problem. But to be honest once k8s allowed to mount it to someone it should allow to modify it too. To be honest I'm not sure. But definitely is you're not able to read volume from other POD it's a problem.
I tried to limit containers/pods created by pv-mounter as much as possible. Maybe in your case it's too much.
Hard to say without knowledge about other stuff that might be limited on your cluster.
We can do another exercise. Are you able to mount that volume from any other container?
Let's say from netshoot one. 
https://github.com/nicolaka/netshoot

**Comment by fenio** [comment]
Mount and write to it.

**Comment by ddrachau** [comment]
Yeah, this ugly debug template does the trick. The pods user is root and that one can touch, rm etc.

apiVersion: v1
kind: Pod
metadata:
  name: my-debug-pod
  namespace: home-assistant
spec:
  containers:
    - name: my-container
      image: praqma/network-multitool
      volumeMounts:
        - mountPath: /app/folder
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: home-assistant-home-assistant-0

could you make the user/userid in the volume-export customizable oder permit root if wanted? :)

**Comment by fenio** [comment]
I can do it probably. But I'm also happy to accept PRs ;)

**Comment by fenio** [comment]
And to be honest I'm really concerned why you have to switch to root to be able to mount that volume. Perhaps some design decisions in your setup are simply bad. In my case it works without switching to root.

**Comment by ddrachau** [comment]
I would be happy to assist with a PR but I am not comfortable to enhance this code and not sure how to test it.

I can mount my volume, but the user is not allowed to modify it.

What's about your permissions in the PVs you edit? Are they more open, so the pe user can edit it? I suppose the helm setup was a bit lazy to do this all by root.

**Comment by fenio** [comment]
Can you share that helm chart so I could experiment with it?

**Comment by ddrachau** [comment]
Of course, I picked a bit older version, so I can migrate my older files, once they are copied to the pv :) I might be that the most recent version is more elegant with regards to the permissions, but I don't think it changed.

[https://artifacthub.io/packages/helm/helm-hass/home-assistant/0.2.33](https://artifacthub.io/packages/helm/helm-hass/home-assistant/0.2.33)

Thanks for your effort!

**Comment by fenio** [comment]
I've just installed that chart and confirmed it mounts read-only fs.
It's because that config directory has rwxr-xr-x permissions.

You can workaround that by changing it:

`kubectl exec -it ha-home-assistant-0 -- /bin/sh`
`chmod o+w .`

Then is should get mounted writable. I tested it.

Anyway I will also think about adding some --root option to mount volumes as root but can't promise when that's gonna happen ;)

**Comment by ddrachau** [comment]
yeah thanks for your support and analysis. Other write permissions should do the trick, but the files will belong to the ve user (whatever id that is). I am not sure if this could lead to problems in the applications. With root, I could chown the files to the appropriate uid and gid :-)

**Comment by fenio** [comment]
Well root will be able to read those files anyway. 
I spent some time today trying to implement --needs-root option but it's not trivial change.
In fact in the past I spent a lot of time to try to get rid need for root ;)
But I've got some ideas how to do it. It's just not my priority.

**Comment by fenio** [comment]
Almost there. I mean I'm there but need to do some cleanup and documentation.

```
[☸ lab:selfhosted] [ needs-root][🐹 v1.22.4]
❯ ~/pv-mounter ./bin/pv-mounter mount selfhosted ha-home-assistant-ha-home-assistant-0 foo
Pod volume-exposer-proxy-jitgi created successfully
Adding ephemeral container volume-exposer-ephemeral-o1v4l to pod ha-home-assistant-0 with volume name ha-home-assistant
Successfully added ephemeral container volume-exposer-ephemeral-o1v4l to pod ha-home-assistant-0
Forwarding from 127.0.0.1:4808 -> 2137
Forwarding from [::1]:4808 -> 2137
Handling connection for 4808
PVC ha-home-assistant-ha-home-assistant-0 mounted successfully to foo

[☸ lab:selfhosted] [ needs-root][🐹 v1.22.4][⏱ 14s]
❯ ~/pv-mounter echo dupa > foo/dupa
zsh: permission denied: foo/dupa

[☸ lab:selfhosted] [ needs-root][🐹 v1.22.4]
❯ ~/pv-mounter ./bin/pv-mounter clean selfhosted ha-home-assistant-ha-home-assistant-0 foo
Unmounted foo successfully
Port-forward process for pod volume-exposer-proxy-jitgi killed successfully
Ephemeral container name is volume-exposer-ephemeral-o1v4l
Process in ephemeral container killed successfully in pod ha-home-assistant-0
Proxy pod volume-exposer-proxy-jitgi deleted successfully

[☸ lab:selfhosted] [ needs-root][🐹 v1.22.4][⏱ 2s]
❯ ~/pv-mounter ./bin/pv-mounter mount --needs-root selfhosted ha-home-assistant-ha-home-assistant-0 foo
Pod volume-exposer-proxy-e27fa created successfully
Adding ephemeral container volume-exposer-ephemeral-maf7r to pod ha-home-assistant-0 with volume name ha-home-assistant
Successfully added ephemeral container volume-exposer-ephemeral-maf7r to pod ha-home-assistant-0
Forwarding from 127.0.0.1:19809 -> 2137
Forwarding from [::1]:19809 -> 2137
Handling connection for 19809
PVC ha-home-assistant-ha-home-assistant-0 mounted successfully to foo

[☸ lab:selfhosted] [ needs-root][🐹 v1.22.4][⏱ 11s]
❯ ~/pv-mounter echo dupa > foo/dupa
```

**Comment by fenio** [comment]
Version 0.7.0 allows to mount as root.

**Comment by fenio** [comment]
@ddrachau Can you confirm it works for you?

**Comment by fenio** [comment]
Can you add your solution to the FAQ section?
Cause I'm not going to modify someones namespaces' labels. I really try to keep my tool as less intrusive as possible but your case with the solution might be helpful for others. Would be great to get PR with info how you dealt with it.

**Comment by fenio** [comment]
I guess that means no.

**Comment by ddrachau** [comment]
Hey sorry, thanks for the reminder, I'll work on it
